#include<stdio.h>
#include<stdlib.h>
#include"socket.h"
#include<string.h>
#include<arpa/inet.h>
#include<unistd.h>

//#define ROOT_SERVER_IP "198.41.0.4"
#define ROOT_SERVER_IP "8.8.8.8"
#define ROOT_SERVER "8.8.8.8"
#define DNS_SERVER "8.8.8.8"
//Types of DNS resource records :)

#define T_A 1 //Ipv4 address
#define T_NS 2 //Nameserver
#define T_CNAME 5 // canonical name
#define T_SOA 6 /* start of authority zone */
#define T_PTR 12 /* domain name pointer */
#define T_MX 15 //Mail server

//DNS header structure
struct DNS_HEADER
{
	unsigned short id; // identification number

	unsigned char rd :1; // recursion desired
	unsigned char tc :1; // truncated message
	unsigned char aa :1; // authoritive answer
	unsigned char opcode :4; // purpose of message
	unsigned char qr :1; // query/response flag

	unsigned char rcode :4; // response code
	unsigned char cd :1; // checking disabled
	unsigned char ad :1; // authenticated data
	unsigned char z :1; // its z! reserved
	unsigned char ra :1; // recursion available

	unsigned short q_count; // number of question entries
	unsigned short ans_count; // number of answer entries
	unsigned short auth_count; // number of authority entries
	unsigned short add_count; // number of resource entries
};

//Constant sized fields of query structure
struct QUESTION
{
	unsigned short qtype;
	unsigned short qclass;
};

//Constant sized fields of the resource record structure
#pragma pack(push, 1)
struct R_DATA
{
	unsigned short type;
	unsigned short _class;
	unsigned int ttl;
	unsigned short data_len;
};
#pragma pack(pop)

//Pointers to resource record contents
struct RES_RECORD
{
	unsigned char *name;
	struct R_DATA *resource;
	unsigned char *rdata;
};

//Structure of a Query
typedef struct
{
	unsigned char *name;
	struct QUESTION *ques;
} QUERY;

struct gethost_reply {
  int type;             /* -1: Not found, 0: Found IP, 1: Found nameserver */
  char details[100];
};

typedef struct gethost_reply ghreply;

char hostcache[100][100];
char ipcache[100][20];
// Next Free Index
int nfi = 0;
int maxi = 0;

union longchar {
  unsigned char a[5];
  long p;
};

typedef union longchar lchar;

ghreply ngethostbyname(unsigned char *, unsigned char *, int, int);
void ChangetoDnsNameFormat (unsigned char*,unsigned char*);
unsigned char* ReadName (unsigned char*,unsigned char*,int*);
char* checkCache(char*);
void addToCache(char*,char*);
void handleDNSRequest(int);


int main()
{
  int sock,revsock,length;
  char resolv[100];
  struct sockaddr_in servaddr=createstructsockaddr_in(AF_INET,"127.0.0.1",0),revservaddr=createstructsockaddr_in(AF_INET,"127.0.0.1",0),addr,addr1;
  fd_set rset;
  sock=socket(AF_INET,SOCK_DGRAM,0);
  revsock=socket(AF_INET,SOCK_DGRAM,0);
  if(bind(sock,(struct sockaddr*)&servaddr,sizeof(servaddr))!=0)
  {
	  printf("DNS SERVER : Unable to bound to UDP port\n");
	  system("proxifier stop");
	  exit(0);
  }
  if(bind(revsock,(struct sockaddr*)&revservaddr,sizeof(revservaddr))!=0)
  {
	  printf("DNS SERVER : Unable to bound to UDP port 54\n");
	  system("proxifier stop");
	  exit(0);
  }
  length=sizeof(addr);
  getsockname(sock,(struct sockaddr*)&addr,&length);
  //sprintf(resolv,"echo \"#Generated by Proxifier.DNS_SERVER\nnameserver 127.0.0.1:%d\" >/etc/resolv.conf",ntohs(addr.sin_port));
  //system(resolv);
  sprintf(resolv,"iptables -w -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:%d",ntohs(addr.sin_port));
  system(resolv);
  length=sizeof(addr1);
  getsockname(revsock,(struct sockaddr*)&addr1,&length);
  sprintf(resolv,"iptables -w -t nat -A OUTPUT -p udp --dport 54 -j DNAT --to-destination 127.0.0.1:%d",ntohs(addr1.sin_port));
  system(resolv);
  while(1) {
  FD_ZERO(&rset);
  FD_SET(revsock,&rset);
  FD_SET(sock, &rset);
    select(max(sock,revsock)+1, &rset, NULL, NULL, NULL);

    if(FD_ISSET(sock, &rset)) {
      handleDNSRequest(sock);
    }
    else if(FD_ISSET(revsock,&rset))
    {
	    char mesg[200];
	    bzero(&mesg,sizeof(mesg));
	    struct sockaddr_in cli;
	    int len=sizeof(cli);
	    recvfrom(revsock,mesg,200,0,(struct sockaddr*)&cli,&len);
	    for(int i=maxi-1;i>=0;i--)
	    {
		    if(strcmp(mesg,ipcache[i])==0)
		    {
			    char send[200];
			    sendto(revsock,hostcache[i],strlen(hostcache[i]),0,(struct sockaddr*)&cli,len);
			    break;
		    }
		    if(i==0)
		    {
	    		sendto(revsock,"0",strlen("0"),0,(struct sockaddr*)&cli,len);
		    }
	    }

    }
  }
}
char* checkCache(char * hostname) {
  int i;
  for(i=maxi-1;i>=0;i--) {
    if(strncmp(hostname,hostcache[i],100) == 0) {
      return ipcache[i];
    }
  }
  return NULL;
}
void addToCache(char* hostname,char* ip) {
  strncpy(hostcache[nfi],hostname,100);
  strncpy(ipcache[nfi],ip,20);
  if(nfi < 99) {
    nfi++;
  }
  else {
    nfi = 0;
  }
  if(maxi < 99) {
    maxi++;
  }
}
void ChangetoDnsNameFormat(unsigned char* dns,unsigned char* host) {
  int lock = 0 , i;
  strcat((char*)host,".");

  for(i = 0 ; i < strlen((char*)host) ; i++) {
    if(host[i]=='.') {
      *dns++ = i-lock;
      for(;lock<i;lock++) {
        *dns++=host[lock];
      }
      lock++; //or lock=i+1;
    }
  }
  *dns++='\0';
}

u_char* ReadName(unsigned char* reader,unsigned char* buffer,int* count)
{
  unsigned char *name;
  unsigned int p=0,jumped=0,offset;
  int i , j;

  *count = 1;
  name = (unsigned char*)malloc(256);
  name[0]='\0';

  //read the names in 3www6google3com format
  while(*reader!=0) {
    if(*reader>=192) {
      offset = (*reader)*256 + *(reader+1) - 49152; //49152 = 11000000 00000000 ;)
      reader = buffer + offset - 1;
      jumped = 1; //we have jumped to another location so counting wont go up!
    }
    else {
      name[p++]=*reader;
    }
    reader = reader+1;
    if(jumped==0) {
      *count = *count + 1; //if we havent jumped to another location then we can count up
    }
  }
  name[p]='\0'; //string complete
  if(jumped==1) {
    *count = *count + 1; //number of steps we actually moved forward in the packet
  }
  //now convert 3www6google3com0 to www.google.com
  for(i=0;i<(int)strlen((const char*)name);i++) {
    p=name[i];
    for(j=0;j<(int)p;j++) {
      name[i]=name[i+1];
      i=i+1;
    }
    name[i]='.';
  }
  name[i-1]='\0'; //remove the last dot
  return name;
}

ghreply ngethostbyname(unsigned char *host,unsigned char *dns_server, int recursion_desired, int print_messages) {
  unsigned char buf[65536],*qname,*reader;
  int i , j , stop , s;
  struct sockaddr_in a;
  struct RES_RECORD answers[20],auth[20],addit[20]; //the replies from the DNS server
  struct sockaddr_in dest;

  struct DNS_HEADER *dns = NULL;
  struct QUESTION *qinfo = NULL;

  ghreply retval;
  retval.type = -2;

  if(print_messages)
    printf("Resolving %s using %s" , host, dns_server);

  s = socket(AF_INET , SOCK_DGRAM , IPPROTO_UDP); //UDP packet for DNS queries

  dest.sin_family = AF_INET;
  dest.sin_port = htons(53);
  dest.sin_addr.s_addr = inet_addr(dns_server); //dns server

  //Set the DNS structure to standard queries
  dns = (struct DNS_HEADER *)&buf;

  dns->id = (unsigned short) htons(getpid());
  dns->qr = 0; //This is a query
  dns->opcode = 0; //This is a standard query
  dns->aa = 0; //Not Authoritative
  dns->tc = 0; //This message is not truncated
  dns->rd = recursion_desired; //Recursion Desired
  dns->ra = 0;
  dns->z = 0;
  dns->ad = 0;
  dns->cd = 0;
  dns->rcode = 0;
  dns->q_count = htons(1); //we have only 1 question
  dns->ans_count = 0;
  dns->auth_count = 0;
  dns->add_count = 0;

  //point to the query portion
  qname =(unsigned char*)&buf[sizeof(struct DNS_HEADER)];
  ChangetoDnsNameFormat(qname , host);
  qinfo =(struct QUESTION*)&buf[sizeof(struct DNS_HEADER) 
    + (strlen((const char*)qname) + 1)]; //fill it

  qinfo->qtype = htons( T_A ); // sending query of A record type
  qinfo->qclass = htons(1); //its internet

  if(sendto(s,(char*)buf,sizeof(struct DNS_HEADER)
        + (strlen((const char*)qname)+1)
        + sizeof(struct QUESTION),0,(struct sockaddr*)&dest,sizeof(dest))
      < 0) {
    perror("sendto failed");
  }

  //Receive the answer
  i = sizeof dest;
  if(recvfrom(s,(char*)buf , 65536, 0, (struct sockaddr*)&dest, (socklen_t*)&i)
      < 0) {
    perror("recvfrom failed");
  }
  dns = (struct DNS_HEADER*) buf;

  //move ahead of the dns header and the query field
  reader = &buf[sizeof(struct DNS_HEADER) + (strlen((const char*)qname)+1) + sizeof(struct QUESTION)];

  if(print_messages) {
    printf("\nThe response contains : ");
    printf("\n %d Questions.",ntohs(dns->q_count));
    printf("\n %d Answers.",ntohs(dns->ans_count));
    printf("\n %d Authoritative Servers.",ntohs(dns->auth_count));
    printf("\n %d Additional records.\n",ntohs(dns->add_count));
  }

  if(recursion_desired && !dns->q_count) {
    retval.type = -1;
  }

  //Start reading answers
  reader = &buf[sizeof(struct DNS_HEADER) + (strlen((const char*)qname)+1) + sizeof(struct QUESTION)];
  stop=0;

  for(i=0;i<ntohs(dns->ans_count);i++)
  {
    answers[i].name=ReadName(reader,buf,&stop);
    reader = reader + stop;

    answers[i].resource = (struct R_DATA*)(reader);
    reader = reader + sizeof(struct R_DATA);

    if(ntohs(answers[i].resource->type) == 1) //if its an ipv4 address
    {
      answers[i].rdata = (unsigned char*)malloc(ntohs(answers[i].resource->data_len));

      for(j=0 ; j<ntohs(answers[i].resource->data_len) ; j++)
      {
        answers[i].rdata[j]=reader[j];
      }

      answers[i].rdata[ntohs(answers[i].resource->data_len)] = '\0';

      reader = reader + ntohs(answers[i].resource->data_len);
    }
    else
    {
      answers[i].rdata = ReadName(reader,buf,&stop);
      reader = reader + stop;
    }
  }

  //read authorities
  for(i=0;i<ntohs(dns->auth_count);i++)
  {
    auth[i].name=ReadName(reader,buf,&stop);
    reader+=stop;

    auth[i].resource=(struct R_DATA*)(reader);
    reader+=sizeof(struct R_DATA);

    auth[i].rdata=ReadName(reader,buf,&stop);
    reader+=stop;
  }

  //read additional
  for(i=0;i<ntohs(dns->add_count);i++)
  {
    addit[i].name=ReadName(reader,buf,&stop);
    reader+=stop;

    addit[i].resource=(struct R_DATA*)(reader);
    reader+=sizeof(struct R_DATA);

    if(ntohs(addit[i].resource->type)==1)
    {
      addit[i].rdata = (unsigned char*)malloc(ntohs(addit[i].resource->data_len));
      for(j=0;j<ntohs(addit[i].resource->data_len);j++)
        addit[i].rdata[j]=reader[j];

      addit[i].rdata[ntohs(addit[i].resource->data_len)]='\0';
      reader+=ntohs(addit[i].resource->data_len);
    }
    else
    {
      addit[i].rdata=ReadName(reader,buf,&stop);
      reader+=stop;
    }
  }

  //print answers
  if(print_messages)
    printf("\nAnswer Records : %d \n" , ntohs(dns->ans_count) );
  for(i=0 ; i < ntohs(dns->ans_count) ; i++)
  {
    if(print_messages)
      printf("Name : %s ",answers[i].name);

    if( ntohs(answers[i].resource->type) == T_A) //IPv4 address
    {
      long *p;
      p=(long*)answers[i].rdata;
      a.sin_addr.s_addr=(*p); //working without ntohl
      if(print_messages)
        printf("has IPv4 address : %s",inet_ntoa(a.sin_addr));
      if(retval.type == -2) {
        retval.type = 0;
        strncpy(retval.details, inet_ntoa(a.sin_addr),100);
      }
    }

    if(ntohs(answers[i].resource->type)==5)
    {
      //Canonical name for an alias
      if(print_messages)
        printf("has alias name : %s",answers[i].rdata);
    }
    if(print_messages)
      printf("\n");
  }

  //print authorities
  if(print_messages)
    printf("\nAuthoritive Records : %d \n" , ntohs(dns->auth_count) );
  for( i=0 ; i < ntohs(dns->auth_count) ; i++)
  {
    if(print_messages)
      printf("Name : %s ",auth[i].name);
    if(ntohs(auth[i].resource->type)==2)
    {
      if(print_messages)
        printf("has nameserver : %s",auth[i].rdata);
      if(retval.type == -2) {
        retval.type = 1;
        strncpy(retval.details,auth[i].rdata,100);
      }
    }
    if(print_messages)
      printf("\n");
  }

  //print additional resource records
  if(print_messages)
    printf("\nAdditional Records : %d \n" , ntohs(dns->add_count) );
  for(i=0; i < ntohs(dns->add_count) ; i++)
  {
    if(print_messages)
      printf("Name : %s ",addit[i].name);
    if(ntohs(addit[i].resource->type)==1)
    {
      long *p;
      p=(long*)addit[i].rdata;
      a.sin_addr.s_addr=(*p);
      if(print_messages)
        printf("has IPv4 address : %s",inet_ntoa(a.sin_addr));
    }
    if(print_messages)
      printf("\n");
  }
  if(retval.type == -2) {
    retval.type = -1;
  }
  return retval;
}


void handleDNSRequest(int sock) {
  unsigned char buf[65536],*qname, *writer, hname[20], *host;
  unsigned short reqid, qcount;
  unsigned int replysize = 0;
  struct DNS_HEADER *dns = NULL;
  struct QUESTION *qinfo = NULL;
  struct RES_RECORD *answer,*auth;
  int stop = 0, recursion_desired;
  char *ip;
  lchar lc;
  ghreply hostdetails, tmphd;
  struct in_addr *addr;

  struct sockaddr_storage clntAddr;
  socklen_t clntAddrLen = sizeof(clntAddr);
  addr = (struct in_addr*)malloc(sizeof(struct in_addr));
  if(recvfrom(sock,(char*)buf , 65536, 0, (struct sockaddr*)&clntAddr, &clntAddrLen) < 0) {
    perror("recvfrom");
  }
  dns = (struct DNS_HEADER*) buf;

  if(dns->qr != 0) {
    return;
  }
  writer = &buf[sizeof(struct DNS_HEADER)];
  // information about request
  host = ReadName(writer,buf,&stop);
  recursion_desired = dns->rd;
  reqid = dns->id;
  qcount = ntohs(dns->q_count);

  // preparing response
  bzero(buf,sizeof(buf));
  dns = (struct DNS_HEADER *)&buf;
  dns->id = reqid;
  dns->qr = 1;
  dns->opcode = 0;
  dns->aa = 0;
  dns->tc = 0;
  dns->rd = 1;
  dns->ra = 1;
  dns->z = 0;
  dns->ad = 0;
  dns->cd = 0;

  dns->rcode = 0;
  // 0 - NoError
  // 3 - NXDomain
  // 4 - NotImp

  dns->q_count = htons(1);
  dns->ans_count = htons(0);
  dns->auth_count = htons(0);
  dns->add_count = htons(0);

  qname =(unsigned char*)&buf[sizeof(struct DNS_HEADER)];
  ChangetoDnsNameFormat(qname , host);
  host[strlen(host)-1] = '\0';
  qinfo =(struct QUESTION*)&buf[sizeof(struct DNS_HEADER) + (strlen((const char*)qname) + 1)];
  qinfo->qtype = htons( T_A );
  qinfo->qclass = htons(1);
  writer = &buf[sizeof(struct DNS_HEADER) + (strlen((const char*)qname)+1) + sizeof(struct QUESTION)];
  replysize = sizeof(struct DNS_HEADER) + (strlen((const char*)qname)+1) + sizeof(struct QUESTION);
  if(qcount != 1) {
    dns->rcode = 4;
  }
  else if((ip = checkCache(host)) != NULL) {        // check cache for hostname
    dns->rcode = 0;   // NoError
    dns->ans_count = htons(1);
  }
  else if(ip==NULL)
  {
					  
						int r,q;
						char m[200];
						r=nfi%10;
						int first;
						if(r==0)
							first=10;
						else 
							first=r;
						q=nfi/10;
						r=q%10;
						int second;
						if(r==0)
							second=10;
						else 
							second=r;
						q=q/10;
						r=q%10;
						int third;
						if(r==0)
							third=10;
						else
							third=r;
						q=q/10;
						r=q%10;
						int fourth;
						if(r==0)
							fourth=10;
						else
							fourth=r;
						sprintf(m,"%d.%d.%d.%d",fourth,third,second,first);
						ip=m;
						addToCache(host,ip);
}

  else if(recursion_desired) {
    hostdetails = ngethostbyname(host, ROOT_SERVER_IP, 1, 0);
    host[strlen(host)-1] = '\0';
    while(hostdetails.type == 1) {
      tmphd = ngethostbyname(hostdetails.details, DNS_SERVER, 1, 0);
      if(tmphd.type == -1) {
        // Not Found
        // Serious Error
        dns->rcode = 2;
      }
      else {
        hostdetails = ngethostbyname(host, tmphd.details, 1, 0);
        host[strlen(host)-1] = '\0';
      }
    }
    if(dns->rcode != 2) {
      if(hostdetails.type == -1) {
        printf("Host %s not found.\n",host);
        ip = NULL;
        dns->rcode = 3; // NXDomain
      }
      else {
        printf("Host %s found using root server.\n",host);
        ip = (char*)malloc(sizeof(char)*20);
        strncpy(ip,hostdetails.details,20);
      }
    }
  }
  else {
    // iterative
    dns->rcode = 0;
    dns->ans_count = htons(0);
    dns->auth_count = htons(1);
    dns->add_count = htons(0);

    auth = (struct RES_RECORD*)malloc(sizeof(struct RES_RECORD));
    strcpy(writer,qname);
    writer = writer + strlen((const char*)qname)+1;
    replysize += strlen((const char*)qname)+1;

    auth->resource = (struct R_DATA*)(writer);
    auth->resource->type = htons(2);
    auth->resource->data_len = htons(strlen(ROOT_SERVER));
    auth->resource->ttl = htonl(146016);
    auth->resource->_class = htons(1);
    writer = writer + sizeof(struct R_DATA);
    replysize += sizeof(struct R_DATA);

    strcpy(writer," ");
    writer = writer + 1;
    replysize++;
    strcpy(writer,ROOT_SERVER);
    writer = writer + strlen(ROOT_SERVER);
    replysize += strlen(ROOT_SERVER);
  }
  if(ip != NULL) {
    // add to cache

    dns->rcode = 0;
    dns->ans_count = htons(1);
    dns->auth_count = htons(0);
    dns->add_count = htons(0);

    answer = (struct RES_RECORD*)malloc(sizeof(struct RES_RECORD));
    strcpy(writer,qname);
    writer = writer + strlen((const char*)qname)+1;
    replysize += strlen((const char*)qname)+1;

    answer->resource = (struct R_DATA*)(writer);
    answer->resource->type = htons(1);
    answer->resource->data_len = htons(4);
    answer->resource->ttl = htonl(1800);
    answer->resource->_class = htons(1);
    writer = writer + sizeof(struct R_DATA);
    replysize += sizeof(struct R_DATA);

    inet_aton(ip,addr);
    lc.p = addr->s_addr;
    writer[0] = lc.a[0];
    writer[1] = lc.a[1];
    writer[2] = lc.a[2];
    writer[3] = lc.a[3];
    writer = writer + 4;
    replysize += 4;
  }
  if(sendto(sock,(char*)buf, replysize, 0, (struct sockaddr*)&clntAddr,clntAddrLen) < 0) {
    perror("sendto failed");
  }
}
